<div id="aboutNST">

<br/><br/><h1>Condiciones del servicio</h1><br/>

<h2>Condiciones del servicio</h2><br/>

<p>1.ACEPTACIÓN DE LOS TÉRMINOS Y CONDICIONES</p>
<p>Le damos la bienvenida a Proyecto NST. Proyecto NST (en adelante “PNST”)  le proporciona sus servicios de acuerdo con las siguientes Condiciones de Servicio (&quot;CDS&quot;), los cuales podrán ser actualizados por PNST sin previa notificación. Usted puede conocer la versión más reciente de las CDS en cualquier momento en: <a href="?controlador=Index&accion=Terminos">terminos</a></p>

<p>Además, cuando utilice un servicios específico de PNST, usted y PNST estarán sujetos a las guías de uso o reglas correspondientes a dichos servicios, las cuales podrán ser anunciadas periódicamente. Las CDS hacen referencia a todas las guías de uso o reglas. </p><br/>

<p>2.DESCRIPCIÓN DEL SERVICIO</p>
<p>PNST proporciona a los usuarios acceso a recursos en línea, en los que se incluyen un instrumento de medición como es la prueba de comprensión lingüística progresiva (en adelante "CLP")email, graficación de resultados, calendarización de pruebas, mantención de curso de alumnos y de grupo de profesores, a la cual se puede ingresar a través del formulario inicial de identificación señalado en la portada del sitio web o aún por desarrollar (el &quot;Servicio&quot;). Usted también entiende y acuerda que el Servicio puede incluir anuncios publicitarios, los cuales son necesarios para que PNST pueda proporcionar el Servicio. Usted entiende y acuerda que el Servicio puede incluir ciertas comunicaciones de PNST, como avisos del servicio, mensajes administrativos y el Boletín de PNST (Novedades PNST); y que estas comunicaciones se consideran parte de la membresía a PNST, y que no podrá renunciar a recibirlas. A menos que se indique explícitamente lo contrario, cualquier nueva aplicación que aumente o mejore el servicio actual, incluso el lanzamiento de nuevas propiedades de PNST, estará sujeta a estas CDS. Usted entiende y acuerda que el Servicio se ofrece &quot;TAL-CUAL-ES&quot; y que PNST no asume ninguna responsabilidad por el retraso, oportunidad en tiempo, eliminación, entrega equivocada o fallo al guardar cualquier comunicación del usuario, o criterios de personalización (&quot;personalization settings&quot;) de cualquier usuario.</p>
<p>Usted tiene la responsabilidad de obtener el acceso al Servicio; dicho acceso puede involucrar a otra entidad y ciertos cargos (como por ejemplo el pago al proveedor de la conexión a Internet o bien pagos por uso de electricidad). Esos cargos deben ser cubiertos por usted, y también incluyen pagos por ver o por recibir anuncios. También es responsabilidad de usted de tener todo el equipo necesario para poder usar el Servicio y acceder al mismo.</p>

<p>Por favor tenga en cuenta que PNST ha creado ciertas áreas del servicio con contenido para docentes. Debe tener por lo menos conocimientos del área para tener acceso y visitar dichas áreas.</p><br/>
<p>3.OBLIGACIONES DEL MIEMBRO</p>
<p>Al usar el Servicio, usted se compromete a: (a) proveer información verdadera, correcta, actualizada, y completa de su persona del modo requerido en el formulario de inscripción del Servicio (siendo dicha información los &quot;Datos de Inscripción&quot;) y (b) mantener y rápidamente actualizar los Datos de Inscripción a fin de que se mantengan verdaderos, correctos, actualizados y completos. Si suministra información que no sea verdadera, correcta, actualizada o completa, o si PNST tiene razones suficientes para sospechar que dicha información no es verdadera, correcta, actualizada o completa, PNST tiene el derecho a suspender o terminar su cuenta y negarle el uso presente o futuro del Servicio (o cualquier parte del mismo). PNST se preocupa por la seguridad e intimidad de sus usuarios, particularmente la de los menores de edad. Por esta razón, los padres de niños menores de 13 años de edad que deseen permitir a sus hijos el acceso al Servicio deberán concentir el ingreso del alumno a PNST. Cuando usted crea una Cuenta de PNST y registra a alumnos menores de edad a la cuenta, usted certifica que tiene por lo menos 18 años de edad y que tiene se hace responsable legal  por la información proporcionada del menor en la cuenta PNST. Al añadir un menor a su Cuenta PNST, también le da autorización para tener acceso al servicio de ejecución de prueba u otro servicio futuro que PNST desarrolle para tal perfil. Por favor recuerde que el Servicio está designado para atraer a una amplia audiencia. Por lo tanto, es su responsabilidad decidir si cualesquiera de los Servicios y/o Contenidos (definido en la Sección 6 abajo) son apropiados para el menor.</p><br/>
<p>4.NORMATIVA DE CONFIDENCIALIDAD DE PNST</p>
<p>Sus Datos de Inscripción y cierta otra información se encuentran sujetos a nuestra Normativa de Confidencialidad. Para mayor información, por favor vea nuestra <a href="?controlador=Index&accion=Privacidad">Política de Privacidad</a>.</p>

<p>5.CUENTA DE MIEMBRO, CONTRASEÑA Y SEGURIDAD</p>
<p>Se le asignará una contraseña y una cuenta una vez completado el proceso de inscripción del Servicio. Usted se responsabiliza de mantener la confidencialidad de su contraseña y cuenta, y de todas las actividades que se efectúen bajo su contraseña o cuenta. Usted se compromete a: (a) notificar inmediatamente a PNST de cualquier uso no autorizado de su contraseña o cuenta o de cualquier otra fallo de seguridad, y (b) asegurarse de que su cuenta sea cerrada al final de cada sesión. PNST no puede y no será responsable por ninguna pérdida o daño que resulte como consecuencia de su incumplimiento de las disposiciones de esta Sección 5. </p><br/>
<p>6.CONDUCTA DEL MIEMBRO</p>
<p>Usted acepta que toda la información, datos, textos, gráficos, mensajes u otros materiales (&quot;Contenido&quot;), ya sea anunciado o transmitido pública o privadamente, son responsabilidad únicamente de la persona que originó dicho Contenido. Esto significa que usted, y no PNST, es responsable exclusivo por todo el Contenido que usted cargue (&quot;upload&quot;), anuncie, envíe por correo electrónico o de cualquier otra forma transmita vía el Servicio. PNST no controla el Contenido anunciado por medio del Servicio, y como tal, no garantiza la veracidad, integridad o calidad de dicho Contenido. Usted comprende que por usar el Servicio, puede estar expuesto a Contenido ofensivo, indecente u objetable. Bajo ninguna circunstancia y en ninguna forma será PNST responsable de ningún Contenido, que incluya y no se limite, a errores u omisiones en algún Contenido, o por alguna pérdida o daño de cualquier tipo que resulte del uso de algún Contenido anunciado, enviado por correo electrónico, o de alguna otra forma transmitido por medio del Servicio.</p>
<p>Usted se compromete a no usar el Servicio para:</p><br/>
<ol style="list-style-type:lower-alpha;">
<li>cargar (&quot;upload&quot;), anunciar, enviar por correo electrónico o de cualquier otra forma transmitir Contenido ilegal, peligroso, amenazador, abusivo, tortuoso, difamatorio, vulgar, obsceno, calumnioso, invasivo del derecho a la intimidad, odioso, o racial, étnica o de cualquier otra forma ofensivo;</li> 

<li>causar daño a menores de edad;</li> 
<li>hacerse pasar por alguna persona o entidad, que incluya pero que no se limite a, a un cargo de PNST, líder de forum, guía o anfitrión, o a hacer declaraciones falsas, o de cualquier otra forma falsificar su asociación con alguna persona o entidad;</li> 
<li>falsificar encabezados o de cualquier otra forma manipular identificadores para desviar el origen de algún Contenido transmitido por medio del Servicio;</li> 
<li>cargar (&quot;upload&quot;), anunciar, enviar por correo electrónico o de cualquier otra forma transmitir algún Contenido que no tiene derecho a transmitir por ley o por relación contractual o fiduciaria (tal como información interna, de propiedad y confidencial adquirida o entregada como parte de las relaciones de empleo o bajo contratos de confidencialidad);</li>
<li>cargar (&quot;upload&quot;), anunciar, enviar por correo electrónico o de cualquier otra forma transmitir algún Contenido que viole alguna patente, marca, secreto comercial, derecho de autor o cualquier derecho de propiedad (&quot;Derechos&quot;) de alguna parte;</li>
<li>cargar (&quot;upload&quot;), anunciar, enviar por correo electrónico o de cualquier otra forma transmitir cualquier anuncio no solicitado o no autorizado, materiales promociónales, correo de solicitación (&quot;junk mail&quot;, &quot;spam&quot;), cartas en cadena (&quot;chain letters), esquemas de pirámides (&quot;pyramid schemes&quot;)o cualquier otra forma de solicitación, con excepción de aquéllas áreas(tales como cuartos de compras &quot;shopping rooms&quot;) que están destinadas para tal propósito;</li>

<li>cargar (&quot;upload&quot;), anunciar, enviar por correo electrónico o de cualquier otra forma transmitir algún material que contenga virus de software, o cualquier otro código de computadora, archivos o programas diseñados para interrumpir, destruir o limitar el funcionamiento de algún software o disco duro de computadora o equipo de telecomunicaciones;</li>
<li>interrumpir el flujo normal de diálogo, hacer que una pantalla se mueva (&quot;scroll&quot;) más rápido de lo que otros usuarios pueden escribir (&quot;type&quot;), o de cualquier otra forma actuar de manera que afecte negativamente la habilidad de otros usuarios para comunicares en tiempo real;</li>
<li>interferir o interrumpir el Servicio, servidores, o redes conectadas al Servicio, o desobedecer cualquier requisito, procedimiento, política o regulación de redes conectadas al Servicio;</li>
<li>acechar o de cualquier otra forma hostigar a otro; o </li>
<li>recoger o recopilar datos personales acerca de otros usuarios.</li>

</ol><br/>
<p>Usted acepta que PNST no pre-selecciona el Contenido, pero que PNST y sus/las personas designadas por PNST tienen a su discreción el derecho, pero no la obligación, de rechazar o remover cualquier Contenido que esté disponible por medio del Servicio. Sin limitación de lo anterior, PNST y las personas designadas por PNST tendrán el derecho de remover cualquier Contenido que viole las CDS o sea de cualquier otra forma objeccionable. Usted acuerda que debe evaluar y que acepta todos aquellos riesgos asociados con el uso de cualquier Contenido, incluyendo su confianza en la veracidad, integridad o uso de dicho Contenido. En este respecto, usted acepta que no podrá depender de ningún Contenido creado por PNST o sometido a PNST, que incluya pero que no se limite a, aquella información contenida en los Boletines de Mensajes y en todas las demás partes del Servicio.</p>
<p>Usted acepta y acuerda que PNST puede conservar y revelar el Contenido si así le es requerido por ley o si en buena fe cree que dicha reserva o revelación es absolutamente necesaria para: (a) cumplir con procesos legales; (b) hace valer las CDS; (c) responder a quejas de que algún Contenido viola los derechos de terceras personas; o (d) proteger los derechos, propiedad, o seguridad personal de PNST, sus usuarios y el público.</p>
<p>Usted entiende que el procesamiento técnico y transmisión del Servicio, incluyendo su Contenido, puede involucrar: (a) transmisiones a través de varias redes; y (b) cambios para el ajuste y adaptación a los requisitos de las redes o dispositivos de conexión.</p><br/>
<p>7.ADVERTENCIAS ESPECIALES PARA USO INTERNO</p>
<p>Teniendo en cuenta la naturaleza global del Internet, usted se compromete a obeceder todas las reglas locales con respecto a la conducta online y Contenido aceptable. En particular, usted se compromete a obedecer todas las leyes aplicables a la transmisión de datos técnicos exportados de Chile o el país en el cual usted reside.</p><br/>
<p>8.CONTENIDO PÚBLICO ANUNCIADO EN PNST</p>
<p>(a) Para estos fines, las &quot;áreas de acceso público del Servicio&quot; son aquéllas con acceso al público en general. Por ejemplo, una área de servicio público del Servicio incluiría mensajes públicos en la portada de PNST, y Boletines de Mensajes PNST, pero no incluiría mensajes de PNST privados.</p>

<p>(b) Con respecto al contenido que usted decida publicar para ser incluido en áreas de acceso público de PNST, aquél que consista en la calendarización de las pruebas CLP, usted otorga a PNST una licencia mundial, libre de regalías (&quot;royalties&quot; o derechos), y no-exclusiva para reproducir, modificar, adaptar y publicar dicho Contenido con el único propósito de mostrar, distribuir y promover el servicio de PNST específico para el cual dicho contenido fue sometido. Esta licencia existirá sólo por el período de tiempo en que usted decida continuar incluyendo dicho contenido en el servicio, y se terminará en el momento en que usted borre dicho contenido del servicio.</p>
<p>(c) Con respecto a cualquier otro Contenido que decida publicar en otras áreas de acceso público del Servicio, usted le otorga a PNST el derecho libre de regalías (&quot;royalties&quot;), perpetuo, irrevocable, no exclusivo y completamente subrogable, y la licencia para usar, reproducir, modificar, adaptar, publicar, traducir, crear obras derivadas del mismo, distribuir, ejecutar y mostrar dicho Contenido (completo o en parte) en todo el mundo y/o incorporarlo a otras obras en cualquier forma, medio o tecnología conocida o que sea desarrollada en el futuro.</p><br/>
<p>9.INDEMNIZACIÓN</p>
<p>Usted se compromete a indemnizar y exonerar a PNST, afiliados, desarrolladores, agentes, asociados (&quot;co-branders&quot;), u otros socios, y empleados de cualquier reclamo o demanda, incluyendo honorarios razonables de los abogados, hecho por una tercera parte derivados del Contenido que Usted presente, anuncie o transmita por medio del Servicio, su uso y conexión al mismo, su violación de las CDS, o su violación de los derechos de terceros.</p><br/>
<p>10.PROHIBICION DE REVENDER EL SERVICIO</p>

<p>Usted se compromete a no reproducir, duplicar, copiar, vender, revender o explotar por cualquier propósito comercial, ninguna parte del Servicio, uso del Servicio, o acceso al Servicio. </p><br/>
<p>11.PRÁCTICAS GENERALES ACERCA DEL USO Y RETENCIÓN</p>
<p>Usted acepta que PNST puede establecer prácticas generales y limitaciones con respecto al uso del Servicio, incluyendo, sin ningún límite, el número máximo de días que los reportes de prueba(después  de haber terminado el 4° año básico de la educación primaria Chilena), anuncios del boletín de mensajes u otros Contenidos instalados han de permanecer en el Servicio, el espacio de disco máximo que será asignado en los servidores de PNST para su beneficio, y el número máximo de veces (y la máxima duración de tales) a las que usted podrá tener acceso al Servicio en un período dado de tiempo. Usted acuerda que PNST no tiene responsabilidad u obligación legal por la eliminación o fallo al guardar reportes u otras comunicaciones, o cualquier otro Contenido mantenido o transmitido por el Servicio. Usted acepta que PNST se reserva el derecho de retirar cuentas que han estado inactivas por un período prolongado de tiempo. Usted además acepta que PNST se reserva el derecho de modificar estas prácticas generales y limitaciones en cualquier momento, a su plena discreción, con o sin previa notificación.</p>
<p>12.MODIFICACIONES AL SERVICIO</p>
<p>PNST se reserva el derecho de modificar, o interrumpir el Servicio o cualquier parte del mismo, temporal o permanentemente, en cualquier momento y periódicamente, con o sin previa notificación. Usted acuerda que PNST no será responsable hacia usted o terceras partes por ninguna modificación, suspensión, o interrupción del Servicio.</p>
<p>13.TERMINACIÓN</p>
<p>Usted acuerda a que PNST, a su plena discreción, puede cancelar su contraseña, cuenta (o alguna parte de la misma) o su uso del Servicio, y retirar y eliminar cualquier Contenido dentro del Servicio por cualquier razón, incluyendo, sin limitación, la falta de uso o si PNST considera que usted ha violado o actuado inconsistentemente con el texto o el espíritu de las CDS. PNST también podrá a su plena discreción y en cualquier momento, interrumpir el Servicio, o alguna parte del mismo, con o sin previa notificación. Usted acuerda que cualquier terminación de su acceso al Servicio bajo alguna sección de estos CDS puede ser efectuada sin notificación previa, y acepta y acuerda que PNST podrá desactivar o borrar inmediatamente su cuenta y toda la información y archivos relacionados con la misma y/o prohibir cualquier nuevo acceso a dichos archivos o al Servicio. Además, usted acuerda que PNST no será responsable hacia usted o tercera parte por cualquier terminación de su acceso al Servicio.</p><br/>

<p>14.ENLACES</p>
<p>El Servicio, o terceros, podrán proporcionar enlaces a otros sitios o recursos en la World Wide Web. Debido a que PNST no tiene control sobre dichos sitios y recursos, usted acepta y acuerda que PNST no será responsable por la disponibilidad de dichos sitios y recursos externos, y no los respalda ni es responsable o tiene obligación legal por el Contenido, comercialización, productos u otros materiales en los sitios o recursos, o disponibles desde los mismos. Además, usted acepta y acuerda que PNST no será responsable ni estará obligado, directa o indirectamente, por ningún daño o pérdida causada por, o en conexión con el uso o confianza en cualquier Contenido, bienes o servicios disponibles a través de cualquier sitio o recurso.</p><br/>

<p>15.DERECHOS DE PROPIEDAD DE PNST</p>
<p>Usted acepta y acuerda que el Servicio y cualquier software necesario usado en conexión con el Servicio (&quot;Software&quot;) contienen bienes e información confidencial que se encuentra protegida por las leyes vigentes de propiedad intelectual y de otra naturaleza. Además, usted acepta y acuerda que el Contenido incluido en anuncios de promotores o información presentada a usted por medio del Servicio o anunciantes, está protegida por los derechos de autor, marcas comerciales, marcas de servicio, patentes y otros derechos y leyes de propiedad. Usted se compromete a no entrar al Servicio por ningún otro medio que no sea la zona interfacial provista por PNST para uso de entrada al Servicio.</p><br/>

<p>16.TÉRMINOS Y CONDICIONES PARA LA COPIA, DISTRIBUCIÓN Y MODIFICACIÓN</p>

<p>1. Esta Licencia se aplica a cualquier programa u otro tipo de trabajo que contenga una nota colocada por el tenedor del copyright diciendo que puede ser distribuido bajo los términos de esta Licencia Pública General. En adelante, «PNST» se referirá a cualquier programa o trabajo que cumpla esa condición y «trabajo basado en el PNST» se referirá bien al Programa o a cualquier trabajo derivado de él según la ley de copyright. Esto es, un trabajo que contenga el programa o una proción de él, bien en forma literal o con modificaciones y/o traducido en otro lenguaje. Por lo tanto, la traducción está incluida sin limitaciones en el término «modificación». Cada concesionario (licenciatario) será denominado «usted».</p>
<p> Cualquier otra actividad que no sea la copia, distribución o modificación no está cubierta por esta Licencia, está fuera de su ámbito. El acto de ejecutar el Programa no está restringido, y los resultados del Programa están cubiertos únicamente si sus contenidos constituyen un trabajo basado en el Programa, independientemente de haberlo producido mediante la ejecución del programa. El que esto se cumpla, depende de lo que haga el programa</p>
<p>2. Usted puede copiar y distribuir copias literales del código fuente del Programa, según lo has recibido, en cualquier medio, supuesto que de forma adecuada y bien visible publique en cada copia un anuncio de copyright adecuado y un repudio de garantía, mantenga intactos todos los anuncios que se refieran a esta Licencia y a la ausencia de garantía, y proporcione a cualquier otro receptor del programa una copia de esta Licencia junto con el Programa.</p>

<p> Puede cobrar un precio por el acto físico de transferir una copia, y puede, según su libre albedrío, ofrecer garantía a cambio de unos honorarios.</p>

<p>3. Puede modificar su copia o copias del Programa o de cualquier porción de él, formando de esta manera un trabajo basado en el Programa, y copiar y distribuir esa modificación o trabajo bajo los términos del apartado 1, antedicho, supuesto que además cumpla las siguientes condiciones:</p>

<p>  1. Debe hacer que los ficheros modificados lleven anuncios prominentes indicando que los ha cambiado y la fecha de cualquier cambio.</p>

<p>  2. Debe hacer que cualquier trabajo que distribuya o publique y que en todo o en parte contenga o sea derivado del Programa o de cualquier parte de él sea licenciada como un todo, sin carga alguna, a todas las terceras partes y bajo los términos de esta Licencia.</p>

<p> 3. Si el programa modificado lee normalmente órdenes interactivamente cuando es ejecutado, debe hacer que, cuando comience su ejecución para ese uso interactivo de la forma más habitual, muestre o escriba un mensaje que incluya un anuncio de copyright y un anuncio de que no se ofrece ninguna garantía (o por el contrario que sí se ofrece garantía) y que los usuarios pueden redistribuir el programa bajo estas condiciones, e indicando al usuario cómo ver una copia de esta licencia. (Excepción: si el propio programa es interactivo pero normalmente no muestra ese anuncio, no se requiere que su trabajo basado en el Programa muestre ningún anuncio).</p>

<p> Estos requisitos se aplican al trabajo modificado como un todo. Si partes identificables de ese trabajo no son derivadas del Programa, y pueden, razonablemente, ser consideradas trabajos independientes y separados por ellos mismos, entonces esta Licencia y sus términos no se aplican a esas partes cuando sean distribuidas como trabajos separados. Pero cuando distribuya esas mismas secciones como partes de un todo que es un trabajo basado en el Programa, la distribución del todo debe ser según los términos de esta licencia, cuyos permisos para otros licenciatarios se extienden al todo completo, y por lo tanto a todas y cada una de sus partes, con independencia de quién la escribió.</p>

<p> Por lo tanto, no es la intención de este apartado reclamar derechos o desafiar sus derechos sobre trabajos escritos totalmente por usted mismo. El intento es ejercer el derecho a controlar la distribución de trabajos derivados o colectivos basados en el Programa.</p>

<p> Además, el simple hecho de reunir un trabajo no basado en el Programa con el Programa (o con un trabajo basado en el Programa) en un volumen de almacenamiento o en un medio de distribución no hace que dicho trabajo entre dentro del ámbito cubierto por esta Licencia.</p>

<p>4. Puede copiar y distribuir el Programa (o un trabajo basado en él, según se especifica en el apartado 2, como código objeto o en formato ejecutable según los términos de los apartados 1 y 2, supuesto que además cumpla una de las siguientes condiciones:</p>

<p> 1. Acompañarlo con el código fuente completo correspondiente, en formato electrónico, que debe ser distribuido según se especifica en los apartados 1 y 2 de esta Licencia en un medio habitualmente utilizado para el intercambio de programas, o</p>

<p> 2. Acompañarlo con una oferta por escrito, válida durante al menos tres años, de proporcionar a cualquier tercera parte una copia completa en formato electrónico del código fuente correspondiente, a un coste no mayor que el de realizar físicamente la distribución del fuente, que será distribuido bajo las condiciones descritas en los apartados 1 y 2 anteriores, en un medio habitualmente utilizado para el intercambio de programas, o</p>

<p>3. Acompañarlo con la información que recibiste ofreciendo distribuir el código fuente correspondiente. (Esta opción se permite sólo para distribución no comercial y sólo si usted recibió el programa como código objeto o en formato ejecutable con tal oferta, de acuerdo con el apartado b anterior).</p>

<p> Por código fuente de un trabajo se entiende la forma preferida del trabajo cuando se le hacen modificaciones. Para un trabajo ejecutable, se entiende por código fuente completo todo el código fuente para todos los módulos que contiene, más cualquier fichero asociado de definición de interfaces, más los guiones utilizados para controlar la compilación e instalación del ejecutable. Como excepción especial el código fuente distribuido no necesita incluir nada que sea distribuido normalmente (bien como fuente, bien en forma binaria) con los componentes principales (compilador, kernel y similares) del sistema operativo en el cual funciona el ejecutable, a no ser que el propio componente acompañe al ejecutable.</p>

<p>Si la distribución del ejecutable o del código objeto se hace mediante la oferta acceso para copiarlo de un cierto lugar, entonces se considera la oferta de acceso para copiar el código fuente del mismo lugar como distribución del código fuente, incluso aunque terceras partes no estén forzadas a copiar el fuente junto con el código objeto.</p>
    
<p>5. No puede copiar, modificar, sublicenciar o distribuir el Programa excepto como prevé expresamente esta Licencia. Cualquier intento de copiar, modificar sublicenciar o distribuir el Programa de otra forma es inválida, y hará que cesen automáticamente los derechos que te proporciona esta Licencia. En cualquier caso, las partes que hayan recibido copias o derechos de usted bajo esta Licencia no cesarán en sus derechos mientras esas partes continúen cumpliéndola.</p>
   <p>6. No está obligado a aceptar esta licencia, ya que no la ha firmado. Sin embargo, no hay hada más que le proporcione permiso para modificar o distribuir el Programa o sus trabajos derivados. Estas acciones están prohibidas por la ley si no acepta esta Licencia. Por lo tanto, si modifica o distribuye el Programa (o cualquier trabajo basado en el Programa), está indicando que acepta esta Licencia para poder hacerlo, y todos sus términos y condiciones para copiar, distribuir o modificar el Programa o trabajos basados en él.</p>

<p>   7. Cada vez que redistribuya el Programa (o cualquier trabajo basado en el Programa), el receptor recibe automáticamente una licencia del licenciatario original para copiar, distribuir o modificar el Programa, de forma sujeta a estos términos y condiciones. No puede imponer al receptor ninguna restricción más sobre el ejercicio de los derechos aquí garantizados. No es usted responsable de hacer cumplir esta licencia por terceras partes.</p>

<p>   8. Si como consecuencia de una resolución judicial o de una alegación de infracción de patente o por cualquier otra razón (no limitada a asuntos relacionados con patentes) se le imponen condiciones (ya sea por mandato judicial, por acuerdo o por cualquier otra causa) que contradigan las condiciones de esta Licencia, ello no le exime de cumplir las condiciones de esta Licencia. Si no puede realizar distribuciones de forma que se satisfagan simultáneamente sus obligaciones bajo esta licencia y cualquier otra obligación pertinente entonces, como consecuencia, no puede distribuir el Programa de ninguna forma. Por ejemplo, si una patente no permite la redistribución libre de derechos de autor del Programa por parte de todos aquellos que reciban copias directa o indirectamente a través de usted, entonces la única forma en que podría satisfacer tanto esa condición como esta Licencia sería evitar completamente la distribución del Programa.</p>

<p>Si cualquier porción de este apartado se considera inválida o imposible de cumplir bajo cualquier circunstancia particular ha de cumplirse el resto y la sección por entero ha de cumplirse en cualquier otra circunstancia.</p>

<p>No es el propósito de este apartado inducirle a infringir ninguna reivindicación de patente ni de ningún otro derecho de propiedad o impugnar la validez de ninguna de dichas reivindicaciones. Este apartado tiene el único propósito de proteger la integridad del sistema de distribución de software libre, que se realiza mediante prácticas de licencia pública. Mucha gente ha hecho contribuciones generosas a la gran variedad de software distribuido mediante ese sistema con la confianza de que el sistema se aplicará consistentemente. Será el autor/donante quien decida si quiere distribuir software mediante cualquier otro sistema y una licencia no puede imponer esa elección.</p>

<p>Este apartado pretende dejar completamente claro lo que se cree que es una consecuencia del resto de esta Licencia.</p>

<p>9. Si la distribución y/o uso de el Programa está restringida en ciertos países, bien por patentes o por interfaces bajo copyright, el tenedor del copyright que coloca este Programa bajo esta Licencia puede añadir una limitación explícita de distribución geográfica excluyendo esos países, de forma que la distribución se permita sólo en o entre los países no excluidos de esta manera. En ese caso, esta Licencia incorporará la limitación como si estuviese escrita en el cuerpo de esta Licencia.</p>

<p>10. La Free Software Foundation puede publicar versiones revisadas y/o nuevas de la Licencia Pública General de tiempo en tiempo. Dichas nuevas versiones serán similares en espíritu a la presente versión, pero pueden ser diferentes en detalles para considerar nuevos problemas o situaciones.</p>

<p>Cada versión recibe un número de versión que la distingue de otras. Si el Programa especifica un número de versión de esta Licencia que se refiere a ella y a «cualquier versión posterior», tienes la opción de seguir los términos y condiciones, bien de esa versión, bien de cualquier versión posterior publicada por la Free Software Foundation. Si el Programa no especifica un número de versión de esta Licencia, puedes escoger cualquier versión publicada por la Free Software Foundation.</p>

<p>11. Si quiere incorporar partes del Programa en otros programas libres cuyas condiciones de distribución son diferentes, escribe al autor para pedirle permiso. Si el software tiene copyright de la Free Software Foundation, escribe a la Free Software Foundation: algunas veces hacemos excepciones en estos casos. Nuestra decisión estará guiada por el doble objetivo de de preservar la libertad de todos los derivados de nuestro software libre y promover el que se comparta y reutilice el software en general.</p>


<br/><p>17.LÍMITE DE LAS GARANTÍAS</p>

<br/><p>USTED EXPRESAMENTE COMPRENDE Y CONVIENE QUE:</p>

<br/><ol style="list-style-type:lower-alpha;">
<li>EL USO DEL SERVICIO LO HACE SU PROPIO RIESGO. EL SERVICIO SE OFRECE &quot;TAL CUAL ES&quot; Y SEGÚN SE ENCUENTRE &quot;DISPONIBLE&quot;. PNST NO OTORGA GARANTÍA DE NINGÚN TIPO, YA SEA EXPRESA O IMPLÍCITA, INCLUYENDO, PERO NO LIMITÁNDOSE, A LAS GARANTÍAS IMPLÍCITAS DE COMERCIALIDAD, APTITUD PARA UN PROPÓSITO EN PARTICULAR, Y NO VIOLACIÓN.</li><br/>

<li>PNST NO GARANTIZA QUE (i) EL SERVICIO SE AJUSTARÁ A SUS REQUISITOS, (ii) EL SERVICIO SERÁ ININTERRUMPIDO, PUNTUAL, SEGURO, O LIBRE DE ERROR, (iii) LOS RESULTADOS QUE PUEDAN SER OBTENIDOS DEL USO DEL SERVICIO SEAN VERACES O FIABLES, (iv) LA CALIDAD DE CUALQUIER PRODUCTO, SERVICIO, INFORMACIÓN, U OTRO MATERIAL COMPRADO U OBTENIDO POR USTED POR MEDIO DEL SERVICIO SE AJUSTARÁ A SUS EXPECTATIVAS Y (v) CUALQUIER ERROR EN EL SOFTWARE SERÁ CORREGIDO.</li><br/>

<li>CUALQUIER MATERIAL DESCARGADO (&quot;DOWNLOADED&quot;) O DE CUALQUIER OTRA FORMA OBTENIDO POR MEDIO DEL USO DEL SERVICIO, LO ES BAJO SU PROPIO RIESGO Y USTED SERÁ RESPONSABLE EXCLUSIVO DE CUALQUIER DAÑO AL SISTEMA DE SU COMPUTADORA O PÉRDIDA DE DATOS QUE RESULTE DE LA DESCARGA (&quot;DOWNLOAD&quot;) DE CUALQUIERA DE ESTOS MATERIALES.</li><br/>

<li>NINGÚN CONSEJO O INFORMACIÓN, YA SEA ORAL O ESCRITO, OBTENIDO DE PNST POR USTED, O POR MEDIO DEL SERVICIO CONSTITUIRÁ GARANTÍA ALGUNA, A NO SER QUE SE ENCUENTRE EXPRESAMENTE ESTABLECIDO EN LAS CDS.</li><br/>
</ol><br/>

<p>18.LÍMITE DE RESPONSABILIDAD</p>
<p>USTED COMPRENDE Y ACUERDA EXPRESAMENTE QUE PNST NO SERÁ RESPONSABLE POR NINGÚN DAÑO DIRECTO, INDIRECTO, INCIDENTAL, ESPECIAL, DERIVADO, O EJEMPLAR, QUE INCLUYA SIN LIMITACIONES, DAÑOS POR PÉRDIDA DE GANANCIA, BUENA FE, USO, DATOS U OTRAS PÉRDIDAS INTANGIBLES (AUN CUANDO PNST HAYA SIDO ADVERTIDO DE LA POSIBILIDAD DE DICHOS DAÑOS), COMO RESULTADO DE: (I) EL USO O IMPOSIBILIDAD DE USAR EL SERVICIO; (ii) EL COSTO DE OBTENCIÓN DE BIENES SUSTITUIBLES Y SERVICIOS RESULTANTES DE CUALQUIER BIEN, DATO, INFORMACIÓN O SERVICIO ADQUIRIDO U OBTENIDO, O MENSAJE RECIBIDO, O TRANSACCIONES REALIZADAS POR MEDIO DEL SERVICIO, O DESDE EL SERVICIO (iii) ACCESO NO AUTORIZADO A SUS TRANSMISIONES, O ALTERACIÓN DE LAS MISMAS, O DE SUS DATOS; (iv) DECLARACIONES O CONDUCTAS DE ALGUNA TERCERA PARTE EN EL SERVICIO; O (v) CUALQUIER OTRO ASUNTO RELACIONADO AL SERVICIO.</p><br/>

<p>19.EXCLUSIONES Y LIMITACIONES</p>
<p>ALGUNAS JURISDICCIONES NO PERMITEN LA EXCLUSIÓN DE CIERTAS GARANTÍAS, O LA LIMITACIÓN DE RESPONSABILIDAD POR DAÑOS INCIDENTALES O DERIVADOS. POR CONSIGUIENTE, ALGUNAS DE LAS LIMITACIONES A LAS SECCIONES 17 Y 18 PODRÍAN NO SERLE APLICABLES.</p><br/>

<p>20.NOTIFICACIÓN</p>
<p>Las notificaciones pueden serle cursadas ya sea por medio del correo electrónico o correo regular. El Servicio también puede proveer notificaciones de los cambios a las CDS, u otros asuntos, mostrándole avisos o enlaces a anuncios en el Servicio.</p><br/>

<p>21.DERECHOS DE AUTOR Y AGENTES DEL DERECHO DE AUTOR</p>

<p>PNST respeta el derecho de propiedad intelectual de otros, y le pide a sus usuarios que hagan lo mismo. Si piensa que su obra ha sido copiada de manera que constituya una violación a los derechos de autor, por favor provea a un Agente de los Derechos de Autor de PNST con la siguiente información:</p><br/>
<ol style="list-style-type:decimal;">
<li>una firma electrónica o física de la persona autorizada a actuar en representación del dueño de los intereses de los derechos de autor.</li>
<li>una descripción de las obras debidamente registradas que usted afirma han sido violadas.</li> 
<li>una descripción de la ubicación en el sitio del material que usted afirma está siendo violado</li> 
<li>su dirección, número de teléfono, y dirección de correo electrónico;</li> 
<li>una declaración estableciendo que de buena fe usted cree que el uso en cuestión no ha sido autorizado por el dueño del derecho de autor, su agente, o la ley;</li>
<li>una declaración bajo pena de perjurio, que la información arriba señalada en su Notificación es verdadera y que usted es el dueño del derecho de autor o está autorizado a actuar en representación del dueño de los derechos de autor.</li> 
</ol>
<p>El Agente de PNST para Notificación de quejas por violación a los derechos de autor puede ser contactado de las siguientes maneras: Por correo ordinario a:</p>

<p>Agente para asuntos de copyright -PNST<br/> 
555 Esperanza<br/>
Región Metropolitana, Santiago, SCL 8350375<br/>
Chile<br/><br/>
Por correo electrónico:<a href="mailto:copyright@proyectonst.cl">copyright[-@-]proyectonst.cl</a><br/><br/>
<br/></p>
<p>Por favor, envié toda comunicación por correo ordinario, correo electrónico en el idioma – Español.</p><br/>


<p>22.INFORMACIÓN GENERAL</p>
<p>Las CDS constituyen el acuerdo completo entre usted y PNST y rige el uso que usted efectúe del servicio de medición de la comprensión lectora de PNST, prevaleciendo sobre cualquier acuerdo anterior entre usted y PNST con respecto del servicio de medición de comprensión lectora de PNST; considerando, sin embargo, que el uso que usted realice del servicio de medición de comprensión lectora de PNST se rige todavía por cualesquiera CDS de PNST o de una entidad afiliada de PNST que usted haya aceptado anteriormente, y no quedan sin efectos. Usted podrá también estar sujeto a términos y condiciones adicionales que podrán ser aplicables cuando usted utilice o adquiera determinados servicios, servicios afiliados, contenido de terceros o software de terceros.  Las CDS y la relación entre usted y PNST serán regidos por las leyes de la República de Chile sin perjuicio de sus provisiones acerca de conflicto de leyes. Usted y PNST acuerdan expresamente en someterse a la jurisdicción personal y exclusiva de las cortes de la República de Chile renunciando a cualquier otro foro que pudiera corresponderles por razón de sus domicilios presentes o futuros. Sin embargo, la falta de PNST de ejercer o hacer efectivo algún derecho o provisión de los establecidos en éstas CDS no constituirá renuncia a dicho derecho o provisión. Si algún tribunal de jurisdicción competente resuelve que alguna disposición de las CDS es inválida, las partes de cualquier modo acuerdan que la corte deberá valorar y darle efecto a la intención de las partes reflejada en dicha disposición, manteniendo las restantes disposiciones de las CDS en pleno vigor y efectividad. Usted acuerda que, sin perjuicio de provisión en sentido contrario en cualquier ley o estatuto, cualquier reclamo o causa de acción resultante del Servicio, o relacionada con el uso del Servicio o las CDS, deberá ser presentada dentro de un (1) año después que dicho reclamo o causa de acción haya sucedido, o de otro modo no podrá ser ejercido en el futuro.</p>
<p>Los títulos de las secciones de las CDS son con fines de referencia y no tienen efectos legales o contractuales.</p><br/>

<p>23.VIOLACIONES</p>
<p>En caso de que usted conozca cualquier violación de las CDS por parte de cualquier tercero deberá notificarlo inmediatamente a nuestro equipo de <a href="mailto:abuso_cds@proyectonst.cl">Atención al cliente (Customer Care)</a></p>

<br/>
<button onClick="javascript:history.go(-1)">Atrás!</a></button>

</div>

